
services:
  lezom-server:
    container_name: ${COMPOSE_PROJECT_NAME}-server
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      mysql:
        condition: service_healthy
      mailpit:
        condition: service_started

  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - lezom-mysql-data:/var/lib/mysql
      - ./lezom.sql:/docker-entrypoint-initdb.d/lezom.sql
    ports:
      - "3306:3306"
    healthcheck:  
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8083:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql

  mailpit:
    container_name: ${COMPOSE_PROJECT_NAME}-mailpit
    image: axllent/mailpit:latest
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  lezom-mysql-data:
